# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-vpc
  description: Terraform Module that defines a VPC with public/private subnets across multiple AZs with Internet Gateways
